version: '3.4'

services:
  lab1.pll:
    image: lab1pll
    build:
      context: .
      dockerfile: lab1/Dockerfile
    depends_on:
      - docker_ntierdemo_db
    hostname: Demo_App_Server  
    container_name: Demo_App_Server  
    networks: 
      app_subnet:        
        ipv4_address: 172.16.1.3           
  docker_ntierdemo_db:
    image: microsoft/mssql-server-linux:latest
    ports: 
      - "14333:1433"
    environment:
      MSSQL_SA_PASSWORD: "Desoutside1"
      ACCEPT_EULA: "Y"
    hostname: Demo_Db_Server  
    container_name: Demo_Db_Server            
    networks: 
      app_subnet:             
        ipv4_address: 172.16.1.4
networks:
  app_subnet:       
    external: true